#:kivy 2.0.0

<MainScreen>:
    MDBoxLayout:
        orientation: "vertical"
        adaptive_height: True
        size_hint: 1,1
        md_bg_color: 0,1,1,1
        MDToolbar:
            title: "COS2PLAN"
            md_bg_color: 0,0.3,0.6,1
        MDLabel:
            text: "BLUEEEEVEE"
            halign: "center"
            size_hint_y: 0.2
            theme_text_color: "Custom"
            text_color: 0, 0, 1, 1
        MDLabel:
            text: "BLUEEEEVEE"
            halign: "center"
            size_hint_y: 0.2
            theme_text_color: "Custom"
            text_color: 0, 0, 1, 1
        MDLabel:
            text: "BLUEEEEVEE"
            halign: "center"
            size_hint_y: 0.2
            theme_text_color: "Custom"
            text_color: 0, 0, 1, 1
        MDLabel:
            text: "BLUEEEEVEE"
            halign: "center"
            theme_text_color: "Custom"
            text_color: 0, 0, 1, 1
        MDLabel:
            text: "BLUEEEEVEE"
            halign: "center"
            theme_text_color: "Custom"
            text_color: 0, 0, 1, 1
        MDLabel:
            text: "BLUEEEEVEE"
            halign: "center"
            theme_text_color: "Error"
        MDLabel:
            text: "BLUEEEEVEE"
            halign: "center"
            theme_text_color: "Custom"
            text_color: 0, 0, 1, 1
                 